name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        working-directory: ./backend
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install dependencies
        working-directory: ./backend
        run: |
          # Assuming you are using a virtual environment or global python on the self-hosted runner
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Restart Backend Service
        working-directory: ./backend
        run: |
          ./venv/bin/uvicorn server:app --host 0.0.0.0 --port 8000
